[project]
name = "nonebot-plugin-impart-plus"
version = "0.3.1"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
authors = [
  { name = "Misty02600", email = "Misty02600@gmail.com" },
]
dependencies = [
  "httpx>=0.27.0,<1.0.0",
  "jinja2>=3.1.6,<4.0.0",
  "nonebot-plugin-alconna>=0.62.1,<0.63.0",
  "nonebot-plugin-htmlkit==0.1.0rc5",
  "nonebot-plugin-localstore>=0.7.0,<1.0.0",
  "nonebot-plugin-orm[default]>=0.8.3,<0.9.0",
  "nonebot-plugin-uninfo>=0.11.1,<0.12.0",
  "nonebot-plugin-uniref>=0.4.0,<0.5.0",
  "nonebot2>=2.5.0,<3.0.0",
  "sqlalchemy>=2.0.20,<3.0.0",
]

[project.urls]
Homepage = "https://github.com/Misty02600/nonebot-plugin-impart-plus"
Issues = "https://github.com/Misty02600/nonebot-plugin-impart-plus/issues"
Repository = "https://github.com/Misty02600/nonebot-plugin-impart-plus.git"

[dependency-groups]
dev = [
  "commitizen>=4.1.0,<5.0.0",
  "git-cliff>=2.11.0,<3.0.0",
  "prek>=0.2.0,<1.0.0",
  { include-group = "lint" },
  { include-group = "test" },
  { include-group = "type" },
]
lint = ["ruff>=0.14.13,<1.0.0"]
test = [
  "nb-cli>=1.7.0,<2.0.0",
  "nonebot-adapter-onebot>=2.4.6,<3.0.0",
  "nonebot2[fastapi]>=2.5.0,<3.0.0",
  "nonebug>=0.4.3,<1.0.0",
  "pytest>=9.0.0,<10.0.0",
  "pytest-asyncio>=1.3.0,<1.4.0",
]
type = ["basedpyright>=1.16.0,<2.0.0"]

[tool.nonebot.plugins]
"nonebot-plugin-impart-plus" = ["nonebot_plugin_impart_plus"]

[tool.nonebot.adapters]
nonebot-adapter-onebot = [
  { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
]

[build-system]
requires = ["uv_build>=0.10.0,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "nonebot_plugin_impart_plus"
