"""initial schema

迁移 ID: f8062f5c90ba
父迁移:
创建时间: 2026-09-04 12:19:09.314430

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f8062f5c90ba"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("nonebot_plugin_impart_plus",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_impart_plus_ejaculationdata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_ref", sa.String(length=255), nullable=False),
        sa.Column("date", sa.String(length=20), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_nonebot_plugin_impart_plus_ejaculationdata")
        ),
        sa.UniqueConstraint(
            "user_ref",
            "date",
            name=op.f("uq_nonebot_plugin_impart_plus_ejaculationdata_user_ref"),
        ),
        info={"bind_key": ""},
    )
    with op.batch_alter_table(
        "nonebot_plugin_impart_plus_ejaculationdata", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_nonebot_plugin_impart_plus_ejaculationdata_user_ref"),
            ["user_ref"],
            unique=False,
        )

    op.create_table(
        "nonebot_plugin_impart_plus_scenedata",
        sa.Column("scene_ref", sa.String(length=255), nullable=False),
        sa.Column("scene_namespace", sa.String(length=128), nullable=False),
        sa.Column("scene_type", sa.String(length=32), nullable=False),
        sa.Column("allow", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint(
            "scene_ref", name=op.f("pk_nonebot_plugin_impart_plus_scenedata")
        ),
        info={"bind_key": ""},
    )
    with op.batch_alter_table(
        "nonebot_plugin_impart_plus_scenedata", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_nonebot_plugin_impart_plus_scenedata_scene_namespace"),
            ["scene_namespace"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_nonebot_plugin_impart_plus_scenedata_scene_type"),
            ["scene_type"],
            unique=False,
        )

    op.create_table(
        "nonebot_plugin_impart_plus_userdata",
        sa.Column("user_ref", sa.String(length=255), nullable=False),
        sa.Column("user_namespace", sa.String(length=128), nullable=False),
        sa.Column("jj_length", sa.Float(), nullable=False),
        sa.Column("last_masturbation_time", sa.Integer(), nullable=False),
        sa.Column("win_probability", sa.Float(), nullable=False),
        sa.Column("is_challenging", sa.Boolean(), nullable=False),
        sa.Column("challenge_completed", sa.Boolean(), nullable=False),
        sa.Column("is_near_zero", sa.Boolean(), nullable=False),
        sa.Column("is_zero_or_neg", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint(
            "user_ref", name=op.f("pk_nonebot_plugin_impart_plus_userdata")
        ),
        info={"bind_key": ""},
    )
    with op.batch_alter_table(
        "nonebot_plugin_impart_plus_userdata", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_nonebot_plugin_impart_plus_userdata_user_namespace"),
            ["user_namespace"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_impart_plus_userdata", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_nonebot_plugin_impart_plus_userdata_user_namespace")
        )

    op.drop_table("nonebot_plugin_impart_plus_userdata")
    with op.batch_alter_table(
        "nonebot_plugin_impart_plus_scenedata", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_nonebot_plugin_impart_plus_scenedata_scene_type")
        )
        batch_op.drop_index(
            batch_op.f("ix_nonebot_plugin_impart_plus_scenedata_scene_namespace")
        )

    op.drop_table("nonebot_plugin_impart_plus_scenedata")
    with op.batch_alter_table(
        "nonebot_plugin_impart_plus_ejaculationdata", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_nonebot_plugin_impart_plus_ejaculationdata_user_ref")
        )

    op.drop_table("nonebot_plugin_impart_plus_ejaculationdata")
    # ### end Alembic commands ###
